# Generated by Django 5.2.7 on 2025-11-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('GER', 'Gerente'), ('REC', 'Recepcionista'), ('LIM', 'Personal de Limpieza'), ('OTR', 'Otro')], default='OTR', max_length=3)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('turno', models.CharField(choices=[('MAN', 'Mañana'), ('TAR', 'Tarde'), ('NOCH', 'Noche')], max_length=4)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('IND', 'Individual'), ('DOB', 'Doble'), ('SUI', 'Suite'), ('FAM', 'Familiar')], max_length=3)),
                ('capacidad', models.IntegerField(help_text='Máximo número de personas.')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disponibles', models.BooleanField(default=True, help_text='Indica si la habitación está lista para ser reservada.')),
                ('piso', models.IntegerField()),
                ('estado_limpieza', models.CharField(choices=[('LIM', 'Limpia'), ('SUC', 'Sucia'), ('MNT', 'En Mantenimiento')], default='LIM', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.TextField()),
                ('habitaciones', models.ManyToManyField(blank=True, help_text='Habitaciones actualmente ocupadas por este huésped.', related_name='huespedes_actuales', to='app_Hotel.habitacion')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Empleado que realizó el registro del huésped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huespedes_registrados', to='app_Hotel.empleado')),
            ],
            options={
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['apellido'],
            },
        ),
    ]
