# Generated by Django 5.1 on 2025-11-19 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hotel', '0002_servicioadicional_reserva_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depósito en Garantía'),
        ),
        migrations.AddField(
            model_name='renta',
            name='empleado',
            field=models.ForeignKey(blank=True, help_text='Empleado que procesó la renta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Hotel.empleado'),
        ),
        migrations.AddField(
            model_name='renta',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Servicios Manuales'),
        ),
    ]
