# Generated by Django 5.1 on 2025-11-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Hotel', '0003_renta_deposito_renta_empleado_renta_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='deposito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='renta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_Hotel.empleado'),
        ),
        migrations.AlterField(
            model_name='renta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
